package com.emotionwheel.app.data

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Guards the shape of assets/emotions.json. It is generated by tools/build_catalog.py,
 * so this is really a check that a hand edit did not break the wheel's structure —
 * every family needs exactly one core and two rings of seven, or sectors go missing.
 */
class EmotionCatalogAssetTest {

    private val emotions: JsonArray = Json
        .parseToJsonElement(File("src/main/assets/emotions.json").readText())
        .jsonObject
        .getValue("emotions")
        .jsonArray

    private fun JsonObject.string(key: String) = getValue(key).jsonPrimitive.content
    private fun JsonObject.int(key: String) = getValue(key).jsonPrimitive.content.toInt()

    @Test
    fun `holds ninety emotions`() {
        assertEquals(90, emotions.size)
    }

    @Test
    fun `every family has one core and two rings of seven`() {
        val byFamily = emotions.groupBy { it.jsonObject.string("family") }
        assertEquals(6, byFamily.size)
        byFamily.forEach { (family, members) ->
            val levels = members.groupingBy { it.jsonObject.int("level") }.eachCount()
            assertEquals("$family core count", 1, levels[1])
            assertEquals("$family middle ring", 7, levels[2])
            assertEquals("$family outer ring", 7, levels[3])
        }
    }

    @Test
    fun `ring positions are zero through six with no gaps`() {
        emotions
            .groupBy { it.jsonObject.string("family") to it.jsonObject.int("level") }
            .filterKeys { it.second != 1 }
            .forEach { (key, members) ->
                val indices = members.map { it.jsonObject.int("index") }.sorted()
                assertEquals("$key positions", (0..6).toList(), indices)
            }
    }

    @Test
    fun `ids are unique and accent free`() {
        val ids = emotions.map { it.jsonObject.string("id") }
        assertEquals(ids.size, ids.toSet().size)
        ids.forEach { id ->
            assertTrue("'$id' should be plain lowercase letters", id.matches(Regex("[a-z]+")))
        }
    }

    @Test
    fun `definitions are present and short enough to scan`() {
        emotions.map { it.jsonObject }.forEach { emotion ->
            val definition = emotion.string("definition")
            val id = emotion.string("id")
            assertTrue("$id has no definition", definition.isNotBlank())
            assertTrue("$id definition is ${definition.length} chars", definition.length <= 200)
        }
    }
}
